### ISSUE TITLE
Resolution problem

### ISSUE THREAD

**Issue by s252805** [ozantezcan/BSUV-Net#1]
When I try a video with resolution (720, 1280) it works perfectly, but with a video of resolution (240, 426) I get an error:

Traceback (most recent call last):
  File "inference.py", line 18, in <module>
    fr = next(iter(vid_loader))
  File "/BSUV-Net/utils/data_loader.py", line 132, in __ iter__
    self.recent_bg_sum += inp["current_fr"]
ValueError: operands could not be broadcast together with shapes (240,426,3) (240,416,3) (240,426,3)

**Comment by ozantezcan** [comment]
Due to max-pooling and interpolation operations in the network, it can only accept the spatial dimensions that are multiples of 16. So, my suggestion for running BUV-Net with (240, 426) resolution is to either resize or zero-pad the frames as (240, 432).
