### ISSUE TITLE
about trained model

### ISSUE THREAD

**Issue by 124399839** [ozantezcan/BSUV-Net#4]
@ozantezcan ，thanks for your greate work of BSUV-Net.However, I have a few questions which confused me a lot, Hope you can comment on it :
Your provided model is trained one of the datasets,which of seg1, seg2， seg3， seg4.... seg18.

Do you use thresholds to process the output of the network of your provided model. What is the threshold value used?

It's hard for me to get as good a result as you according to the description of the paper.

**Comment by ozantezcan** [comment]
Both of the models are trained using [CDNet2014 dataset](uhttp://www.changedetection.net/). Training doesn't use any thresholding but during inference we threshold the output by 0.5 to binarize the results. I hope this answers the question.

**Comment by 124399839** [comment]
Great, thanks.

**Comment by xavibou** [comment]
Hi, thank you for the code :). In regards to BSUV-Net 2.0, I assume the provided pre-trained model has been trained on CDNet2014 as well. Which specific sequences of the available model have been used to train? Or all of them were used? 
Best.
